build:
    image: registry.gitlab.com/robigalia/runner:latest
    script: 
        - "xargo build --target i686-sel4-unknown --no-default-features"
        - "xargo build --target arm-sel4-gnueabi --no-default-features"
        - "xargo build --target arm-sel4-gnueabihf --no-default-features"
        - "cargo test"
        - "cargo test --release"
verify_signatures:
    image: ubuntu:16.10
    script:
        - apt update
        - apt install --assume-yes python-pexpect gnupg2 git
        - git clone --depth=1 https://gitlab.com/robigalia/meta
        - gpg2 --list-keys # to force it to create GNUPGHOME instead of racing in the pipe below
        - gpg2 --export --no-default-keyring --keyring ./meta/.gnupg/pubring.kbx | gpg2 --import
        - gpg2 --list-keys --fingerprint --fingerprint --verbose
        - ./meta/verify-signatures.py HEAD ./meta/.mailmap
